## Authorizations
# Uncomment out the merging for each enviornment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# enviornment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    - cn=admins,ou=groups,dc=test,dc=com
    - cn=users,ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Enviornments

#ldap = Net::LDAP.new host: '192.168.1.37', port: 389, base: "CN=Administrator,CN=Users,DC=endura,DC=enduraproducts,DC=com", auth: {method: :simple, username: 'Endura\\jmilam', password: 'jm10102'}
development:
  host: 192.168.1.37
  port: 389
  attribute: uid #cn
  base: CN=Administrator,CN=Users,DC=endura,DC=enduraproducts,DC=com
  admin_user: dc=Endura\Administrator
  admin_password: Mwt8G8pz!
  ssl: true
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: false
  # <<: *AUTHORIZATIONS

production:
  host: localhost
  port: 636
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: true
  # <<: *AUTHORIZATIONS